[package]
name = "dc1394-debayer"
description = "debayering from libdc1394"
version = "0.1.0"
build = "build.rs"
license = "LGPL"
authors = ["Damien Douxchamps <ddsf@douxchamps.net>"]

[dependencies]

[build-dependencies]
gcc = "0.3.41"
